window.onload = function(){

	//hide the warning at the start
	document.getElementById('warning').style.display = 'none';

	//two functions below based on formula chosen.
	var eplay = function(weight, reps){
		var max = weight*(1+reps/30);

		max = Math.round(max);

		return max;
	}

	var brzycki = function(weight, reps){

		var max = weight * (36/(37-reps));

		max = Math.round(max);

		return max;

	}

	//calculate is  called when the button is pressed.
	var calculate= function(){
		var result = document.getElementById("result");
		var warning = document.getElementById('warning');

		var weight = document.getElementById("weight").value;
		var reps = document.getElementById("reps").value;


		if(weight<=0 || reps <=0){			
			warning.innerHTML = "Please enter only positive numbers for both fields."
			warning.style.display = 'block';
		}else if (reps >20){
			warning.innerHTML = "Please enter only rep count under 20"
			warning.style.display = 'block';
		}else{

			if (reps > 10){
				
				warning.innerHTML = "Please note: accuracy decreases significantly past 10 reps."
				warning.style.display = 'block';
			}else{	
				warning.style.display = 'none';
			}

			var formOne = document.getElementById("eplay").checked;

			if (formOne){
				result.innerHTML = eplay(weight,reps);
			}else{
				result.innerHTML = brzycki(weight,reps);
			}

			clearTable();
			createTable(result.innerHTML);
		}
		
	}

	document.getElementById("calculate").addEventListener("click", calculate);


	//table is to be autogenerated now up to 10. 

	var createTable = function(max){	

		var table = document.getElementById("statTable");
		var rowOne = table.insertRow(0);
		var rowTwo = table.insertRow(1);

		var cell = rowOne.insertCell(0);
		cell.innerHTML="Percentage"
		cell.classList.add("repH");

		var res = rowTwo.insertCell(0);
		res.innerHTML = "Weight";
		res.classList.add("repH");

		for (var i = 1; i<=10; i++){
			var cell = rowOne.insertCell(i);			
			cell.innerHTML = 100-5*i +"%";			
			cell.classList.add("repH");

			var res = rowTwo.insertCell(i);
			res.innerHTML = Math.round((100-5*i)*max/100);
			res.classList.add("repH");
		}

	}

	var clearTable = function(){
		var table = document.getElementById("statTable");
		table.innerHTML = "";
	}

}